server:
  port: 8080

spring:
  application:
    name: is1
  datasource:
    url: jdbc:postgresql://localhost:5432/studs
    username: s367054
    password: yLm1ilcVMgppkgJw
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

minio:
  url: http://localhost:9000
  access:
    key: minioadmin
  secret:
    key: minioadmin
  bucket:
    name: parquet-files